### ISSUE TITLE
Suggested visual and simulation enhancements.

### ISSUE THREAD

**Issue by jsimpso81** [superhornets/FRC-Simulations#1]
The attached zip file contains some suggested visual and simulation enhancements.  This is slightly newer than the one I sent via chief delphi mail.  The following changes were made:
1) added color wheel visual (main)
2) added arm visual (main)
3) reversed color direction to correspond to wheel picture (sensor)
4) added some motor start/stop lag (sensor)
5) added some random wheel slip.
6) added some simulated starting friction for wheel and arm motors.
Do with this as you want....
[2020 Control Panel_JAS_R1.zip](https://github.com/superhornets/FRC-Simulations/files/4877131/2020.Control.Panel_JAS_R1.zip)

**Comment by JonathanLindsey** [comment]
Thanks @jsimpso81 those are really good ideas! I haven't had a chance to open this latest change yet but I did look at the one you sent via CD.

I noticed a few things I think could be made a bit better in your changes. Not that I don't like them at all, they're awesome! Just a few best practices. Could you read the CONTRIBUTING.md file I added yesterday evening. Points 1 and 5 your good on.

Also, let me know if you'd like to know how to turn this into a Pull Request.

P.S. Thanks for the trajectory library you've put on CD recently! I looked at it before and mean to look into it farther. Looks awesome!

**Comment by jsimpso81** [comment]
I'm just learning how to use github....  I've learned enough to ask some questions.
  1) I installed git and the github desktop.  Fortunately I had one computer with 64 bit windows to do this on.  Other than configuring the option to separate source and compiled code, I didn't configure anything else in LabVIEW for git.  I think the next step would be to configure LabVIEW for the source code control, but it looks like this isn't needed (for now).
2) I think the  work flow is:  a) do a pull request b) make changes to my local copy, c) commit the changes to the local git. d) either make a github branch then push there or push to the master copy.  Either way I assume that you would then have to approve and merge the changes into the master????
3) I changed things to fit the guidelines.  I hadn't seen them.  
I'll go ahead and do the pull, but I'll wait to hear back before pushing anything back.
thanks
jim
Jim

**Comment by jsimpso81** [comment]
Ok...  Step a was to clone then pull

**Comment by JonathanLindsey** [comment]
1. I actually recommend [GitExtensions](https://gitextensions.github.io/) rather than GitHub Desktop which looks like it is still 32-bit. It gives you a tree representation of of the commit history. Anyway, the git GUI you use doesn't really matter so just use whatever works for you. Here are some [more Git GUIs](https://git-scm.com/download/gui/win). The options for source code control that are built into LabVIEW are for Subversion (a.k.a. SVN) not Git so don't worry about them. Having turned on the option to separate source and compiled code is good.
2. I think you're _gitting_ the process down. However, I don't think you'll be able to push just yet because you would be pushing directly to the Super Hornet's copy. First you need to fork the project under your own GitHub username by clicking the ![image](https://user-images.githubusercontent.com/18510187/87233293-ad161f00-c38b-11ea-883b-ff0d0f718908.png) button in the top right corner of this page. This will take you to https://github.com/jsimpso81/FRC-Simulations.
Now you'll want to set your existing local copy of the repo to point to your online copy but still have a reference to the Super Hornets copy. Do this in GitHub Desktop by opening the Repository drop-down from the top of the window and selecting Repository settings then change the Primary remote to https://github.com/jsimpso81/FRC-Simulations.git. Apparently GitHub desktop runs these 2 command prompt commands in the background when you do this.
```
git remote set-url origin https://github.com/jsimpso81/FRC-Simulations.git
git remote add upstream https://github.com/superhornets/FRC-Simulations.git
```
I recommend doing a fetch in GitHub desktop immediately after. This is equivalent to `git fetch --all`.
You should make a separate branch locally (on your computer) but I think things will work out even if you don't.
Then you can push and start the pull request.

**Comment by JonathanLindsey** [comment]
Here is a good video on the Pull Request workflow. The second half of the video it shows the process in GitKraken yet another Git GUI.
https://www.youtube.com/watch?time_continue=98&v=2VX1ISk9XH8&feature=emb_logo

**Comment by jsimpso81** [comment]
I think I did the fork, pushed my changes to the fork and created a pull request.  Do with these what you want.  Jim
